web/mysite/myfirstwapp/urls.py
from django.urls import path
from . import views


app_name = 'myfirstwapp'
urlpatterns = [
    path('', views.index, name='index'),
    #path('<int:question_id>/', views.detail, name='detail'),
    
    path('<int:question_id>/results/', views.results, name='results'),
    
    path('<int:question_id>/', views.vote, name='vote'),
    ]
    

web/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('myfirstwapp/', include('myfirstwapp.urls')),
    path('admin/', admin.site.urls),
    
]

web/mysite/myfirstwapp/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    
    question_text = models.CharField(max_length=200)
    pub_date = models.DateField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

web/mysite/myfirstwapp/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader

from .models import Question, Choice

def index(request):
    q_list = Question.objects.order_by('-pub_date')[:3]
    temp = loader.get_template('./myfirstwapp/index.html')
    #out = ' '.join([q.question_text for q in q_list])
    context = {

        'latest_question_list': q_list,
    }
    return HttpResponse(temp.render(context, request))


def detail(request, question_id):
    try:
        q = Question.objects.get(id=question_id)
    
    except Question.DoesNotExist:
        raise Http404("Invalid Question") 
    return HttpResponse("You're Looking at this Question {}".format(question_id))


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'myfirstwapp/results.html', {'question': question})

def vote(request, question_id):
    
    question = get_object_or_404(Question, id=question_id)
    
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'myfirstwapp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('myfirstwapp:results', args=(question.id,)))
    #return HttpResponse("Voting on Question {}".format(question_id))





# Create your views here.

web/mysite/myfirstwapp/templates/myfirstwapp/detail.html
{% extends "myfirstwapp/header.html" %}

{% block poll %}
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}



<form action="{% url 'myfirstwapp:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

{% endblock %}

web/mysite/myfirstwapp/templates/myfirstwapp/header.html
<!DOCTYPE html>
<header> 

    

    <title> Hello There </title>
    {% load staticfiles %}
    <link rel='stylesheet' href="{% static 'css/bootstrap.min.css' %}" 
    type="text/css"/>
   
</header>

</html>

{% block poll %} {% endblock %}

web/mysite/myfirstwapp/templates/myfirstwapp/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/myfirstwapp/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

web/mysite/myfirstwapp/templates/myfirstwapp/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'myfirstwapp:detail' question.id %}">Vote again?</a>